// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonApp.Infrastructure.Data;

#nullable disable

namespace PokemonApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240912115759_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PokemonApp.Domain.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpriteBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TreinadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TreinadorId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokemonApp.Domain.Entities.Treinador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Treinadors");
                });

            modelBuilder.Entity("PokemonApp.Domain.Entities.Pokemon", b =>
                {
                    b.HasOne("PokemonApp.Domain.Entities.Pokemon", null)
                        .WithMany("Evolucoes")
                        .HasForeignKey("PokemonId");

                    b.HasOne("PokemonApp.Domain.Entities.Treinador", null)
                        .WithMany("CapturadosPokemons")
                        .HasForeignKey("TreinadorId");
                });

            modelBuilder.Entity("PokemonApp.Domain.Entities.Pokemon", b =>
                {
                    b.Navigation("Evolucoes");
                });

            modelBuilder.Entity("PokemonApp.Domain.Entities.Treinador", b =>
                {
                    b.Navigation("CapturadosPokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
